# Site Info
title: "사라진 기억들에게"
tagline: "사라진 기억들에게"
description: ""
baseurl: ""
url: http://mojaeya.github.io
logo: "/public/logo.png"

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: "/blog/page:num"
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: mojaeya
  description: mojaeya ( Hojae Kim )<br>"배움을 포기하는 순간 늙기 시작한다."
  gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    #linkedin:  https://www.linkedin.com/in/lizhihao
    github: https://github.com/mojaeya
    facebook: ttps://www.facebook.com/ghwo5838
    email: mailto:mojaeya@gmail.com
# Navigation (2nd level links supported)
nav:
  # Home:
  #   - '/blog/'
  # About:
  #   - "/about/"
  Categories:
    - "/"
    - { CS: "/blog/categories/cs" }
    - { HTML: "/blog/categories/#html" }
    - { CSS: "/blog/categories/#css" }
    - { JavaScript: "/blog/categories/#javascript" }
    - { Vue.js: "/blog/categories/#vue.js" }
    - { React.js: "/blog/categories/#react.js" }
    - { Node.js: "/blog/categories/#node.js" }
    - { MySQL: "/blog/categories/#mysql" }
    - { MongoDB: "/blog/categories/#mongodb" }
    - { Algorithm: "/blog/categories/#algorithm" }
    - { AWS: "/blog/categories/#aws" }
    - { Git: "/blog/categories/#git" }
    - { etc: "/blog/categories/#etc" }
  # Search:
  #   - "/search/"

# Where are tags and categories displayed
tag_page: "/blog/tags/"
category_page: "/blog/categories/"

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: "UA-00000000-1" # leave blank if you don't want google analytics

plugins: [jekyll-paginate]
